### ISSUE TITLE
copia file

### ISSUE THREAD

**Issue by FabioZTessitore** [August0/caratteri#1]
dai un'occhiata al file copia_file.c
cerca di capire cosa fa e spiegamelo

**Comment by August0** [comment]
getchar ci fa inserire dei valori in c e ogni volta che questo non è uguale
al terminale ('\0') noi visualizziamo a video il valore inserito...

Il giorno 21 dicembre 2015 18:19, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Prima di tutto il carattere \0 si chiama terminatore e non terminale ...

Seconda cosa, non compare da nessuna parte. Il ciclo termina quando si incontra EOF che rappresenta la fine del file (End Of File).

Terza cosa, c'è un'assegnazione all'interno della condizione del ciclo while. Avevi già incontrato niente del genere?

**Comment by FabioZTessitore** [comment]
Prendi ad esempio una instruzione del tipo:

``` C
int a, b, c;
a = b = c = 10;
```

Dovresti sapere che serve ad assegnare il valore 10 alle variabili intere `a, b, c`.
Nel dettaglio quello che succede è che viene effettuata prima l'operazione

``` C
c = 10
```

Nel linguaggio C una **assegnazione vale il valore assegnato**, in altre parole tutta l'istruzione `c = 10` **vale** il valore assegnato 10.
Questo permette di proseguire nella catena:

``` C
a = b = (c = 10)   --->  a = b = 10  ---> a = (b = 10)  ---> a = 10
```

**Comment by FabioZTessitore** [comment]
Nel nostro caso, come condizione del ciclo while c'è:

``` C
(c=getchar())!=EOF
```

Quindi prima viene eseguita la funzione `getchar()` (legge un carattere dal buffer di input), poi il carattere letto viene assegnato a `c`.
Infine tutta l'istruzione `(c=getchar())` **vale** il carattere letto che può essere confrontato con EOF per stabilire se nel file di input ci sono ancora caratteri da leggere.
