### ISSUE TITLE
Conta Spaziature

### ISSUE THREAD

**Issue by FabioZTessitore** [August0/caratteri#2]
Sulla base dei programmi di esempio crea un programma conta_spaziature.c che conta (separatamente) gli spazi, le tabulazioni e i newline

**Comment by FabioZTessitore** [comment]
problemi?

**Comment by FabioZTessitore** [comment]
ti sei ripreso dal Natale? c'è questo esercizio che ti aspetta

**Comment by FabioZTessitore** [comment]
Ci sei? Devi ancora fare questo esercizio. Qualcosa non va?

**Comment by August0** [comment]
Tutto ok sono operativo!

Il giorno 13 gennaio 2016 18:37, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Bene, aspetto l'esercizio conta_spaziature.c

**Comment by FabioZTessitore** [comment]
Questo esercizio non l'hai piu' fatto
